name: Build and deploy ASP app to Azure Web App - medresearchninja

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DFA7EDCA87B34C30A3F5A810828F9AAC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2AA4741E2945421FB24AD0161FDE1871 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4DAFE6F43D5242D5B906F0C4FCB51BDE }}

      - name: Zip the web site folder
        shell: pwsh
        run: |
          Compress-Archive -Path medresearchninja.org-code\* -DestinationPath website.zip -Force
          $size = (Get-Item website.zip).Length / 1MB
          Write-Host "ZIP size: $size MB"

      - name: Deploy via Azure CLI
        shell: pwsh
        run: |
          az webapp deploy `
            --resource-group MedResearchNinja `
            --name medresearchninja `
            --src-path website.zip `
            --type zip `
            --async false
